### PR TITLE
Extracted exit node list from the main execution script.

### PR DESCRIPTION
**Pull request by Pysis868**
This change should allow for more flexible tool operation and easier automation, as well as de-cluttering the change history for the distinct main execution script, all for the future.

### CODE REVIEW

**Comment by MattSurabian** [comment]
Temporary :-1:

We should update `install.sh` to ensure this gets copied somewhere, like `$HOME/.config/proxpn/exit_nodes.sh` and the manual install instructions in the readme should mention this file and its purpose.

Also, on a broader level I've been resisting this because I liked that the entire thing was contained in a single file. Bash is the only language I feel this way about, and perhaps in the broader picture that's wrong, but to me it made it more approachable for new folks and avoided adding another outside link.

Thinking a little more about it though, there's something to be said for releasing updates that clearly don't modify the program logic at all. A change like this could also help @thecodefactory use this with AnonVPN if that's still something on their radar.

What do you think?

**Comment by thecodefactory** [comment]
@MattSurabian Don't know.  I think re-writing this as a python script would be the cleanest and easiest to read and extend, but is an effort and adds a (python) dependency.  As it stands, a single bash script is convenient.

I still use proxpn and anonvpn on occasion, but I've shifted my primary VPN usage to another provider some time ago.  I do think this project could use more visibility as it was difficult to find a simple way to get started after signing-up (for those of us that use GNU/Linux exclusively).

**Comment by MattSurabian** [comment]
Thanks for the reply @thecodefactory, hope all is well.

With regards to rewriting in python, I'm more inclined to rewrite in something like Go and release standalone binaries. The only trick there is most sysadmin types that might use this may not trust the binary. :shrug:

Hmmm, @Pysis868 could you outline the main automation benefit you see to splitting this file out?

**Comment by Pysis868** [comment]
@MattSurabian Copied?  I believe keeping this in the application directory to be fine, as it is application data, and 'should' not need to be customized per user.

Idk about the 'same file' approach man, I think that's just your feeling :).  I think as long as the user is able to conveniently run the `proxpn` command on the PATH, that is the most they will worry about this project's files.  That, and knowing to run the install command once by reading the README.

I did make the changes in the effort of the developers.  I do like things such as the commit history and maintainability of the code to be more discrete, and that should make files easier to maintain.  It would also save some effort now to not only allow, but later implement this automation.  I wonder if even during this recent usage I went through, if one of the endpoints was still functional, or if we need to update the exit nodes again.  Ideally this would be something that runs often with the main use of the tool, downloading the XML if there is a newer timestamp, then parsing and generating Bash code for a really up-to-date list.

@thecodefactory Don't think Python will help anything, maybe just that you may be used to working with the language.  I think it's certainly within the capability of the Bash language to support multiple VPN providers, if that is the future of this project, whether it be a separate script entry-point, parameter, or etc.
With that in mind, if you wanted to make using Python a non-functional requirement, you could simply make another repo using the other programming language to emulate the functionality of this one.

**Comment by MattSurabian** [comment]
Not all users keep the application directory or install with the symlink option though. There's a usecase where someone downloads this repo as a zip, runs the installer script and then trashes everything. Checkout this section of the installer https://github.com/MattSurabian/proxpn-bash-client/blob/master/install.sh#L95-L109 Specifically 103-108.

**Comment by Pysis868** [comment]
Added the change in.

There could be an argument for doing this system-wide, as it maps to the service, which is not user-specific, and users would already need privileged access to run this project anyway.

Although I went ahead and just used the user folder for now.

**Comment by Pysis868** [comment]
o, and @MattSurabian just not having to manually edit the list in shell code every time:
- Risk syntax errors, however slight, delaying update progress.
- Originally, support maintenance is implied by the project contributors, when:
  - if there were a script that the project runs, it could be included, and the users could try running the script if they ever had trouble with using certain exit nodes, as a debug step.
  - This also removes the greater 'immediacy' that would be required from the contributors needing to quickly respond, and even pre-empt, changes to the exit nodes list.
  - It could possibly even be added as a build step, something from an automation server that usually checks build effectiveness, could also commit back an updated file, when needed.
  - All of these points lead to better adoption for users that could have less struggles when these methods are implemented.

**Comment by MattSurabian** [comment]
Yeah I was thinking it could be put into `/etc/proxpn/exit_nodes.sh` which I think is the more correct way to do it, but it's more sprawl and there's potential for folks to maybe curate their own exit node list? Heh IDK.

Thanks for making the update, are you comfortable doing the rebase to remove conflicts or would you like me to do that?

**Comment by Pysis868** [comment]
I could give the rebase a try, I guess I just hadn't done it before working with remotes on GitHub (multiple ones, and GitHub style?).  Anyway, I have pulled master from your repo, and I would just put it on that latest commit?  If so, I can give it a try, hopefully tonight.

I can also make the next change to use the system-wide path **instead**.

How about, if you think the feature for users to curate their own lists is important enough, we can add that as as separate feature, possibly sourcing both in a certain order.  This may also come if install considerations if we wanted to make the set-up more 'convenient', which is also why those changes could be done separately.  Heck, go ahead and create the issue, and if it won't be done without more support from the community, we can leave it in a closed state or something as reference that it at least came up.

**Pull request closed without merging**
