### PR TITLE
Adds Anonvpn support

### PR DESCRIPTION
**Pull request by thecodefactory**
Anonvpn.io is an OS X/Win/iOS/Android based VPN currently having a pay what you want sale for a litetime subscription:

https://deals.slashdot.org/sales/pay-what-you-want-vpn-lifetime-bundle

https://www.anonvpn.io/

This pull requests adds a parallel anonvpn script and install-anonvpn installer script for users wishing to use their services on GNU/Linux.  Anonvpn.io is related to ProXPN in terms of infrastructure, so this was not a far stretch, but perhaps not under the scope of this project.

### CODE REVIEW

**Comment by MattSurabian** [comment]
This is interesting! I'm not surprised their infrastructure is so similar, and it kind of makes me wonder if this project should morph into a generic OpenVPN client for Linux that supports various providers?

**Comment by thecodefactory** [comment]
That, I don't know.  I couldn't estimate how many other VPN providers share proxpn like infrastructure.  And personally, I think seeking VPN providers that offer a similar configuration sounds dull :wink: 

The reason I believed Anonvpn is so heavily integrated with ProXPN is because if you look at this link for the deal:

https://deals.slashdot.org/sales/pay-what-you-want-vpn-lifetime-bundle

It's offered "By proXPN".  So I decided to checkout their release and sure enough, the package looks very similar and I was able to test all of the endpoints contained in it.  Since it was a minor modification and something that I'm now using that proved useful, I thought the pull request was appropriate for anyone interested.

**Comment by MattSurabian** [comment]
Huh... I wonder what's going on there. When I first read this I thought it was similar only in the fact that it was also providing a set of OpenVPN exit nodes to emerge from. Though it really seems like it's a related company in some way.

As far as making this a more generic tool I meant along the lines of it being smart enough to ask the user which provider they wanted to use, likely after checking for multiple configuration files instead of having to have a completely different script and installer exposed.

As written I think this PR would be better as it's own repository just for anonvpn.

**Comment by thecodefactory** [comment]
Yeah, hard to say and I could go either way on that.  Prompting and asking each time which provider to use will get annoying if you only have an account on one.  If I do end up making a separate repo, I would likely re-write and merge the installer and runtime into a single script.

**Comment by MattSurabian** [comment]
Yeah my thought is like, maybe the script only prompts if it detects the configuration file? Also a big use case in my mind (not sure if folks do this) is locking down the script via passed in options and interacting with it via an alias instead of going through the interactive prompts every time, so it would be more like `--provider|-p anonvpn`

**Comment by thecodefactory** [comment]
I like that idea.  Also, perhaps a single config file that stores not only the login info, but the configured provider info as well as each login?  So the installer could first ask about proxpn and store configs and credentials, then ask about anonvpn, and store those if any, or something like that.

**Comment by MattSurabian** [comment]
With UDP support landed and all the additional exit nodes that are now supported I'm thinking the anonVPN support should just be done in a forked repo that replaces the conf file and exit node listing. Thoughts?

**Comment by thecodefactory** [comment]
Not a problem.  The pull request as posted meets my needs -- perhaps not in the best interest of this project though.

**Comment by MattSurabian** [comment]
You should definitely post it as a fork, I'm sure it will meet other's needs too!

**Comment by bradfordcasey** [comment]
@Alexanderblaq91 @thecodefactory 
I just wanted to chime in and say that I am having exactly the same problem. It is not an issue with setup, but rather with limitations of the Android VPN client. The client has a character input limit for the username/login field. Anonvpn requires an 8-char preceding tag for one's login, which quickly makes even a relatively normal email address too long to fit in the input field. As a result, one can't actually login. 
As Alexander noted, anonvpn's support appears to be literally nonexistent (poking around suggests that proxpn has the same support function). Disappointing, as this could easily be remedied by adding an "update email/username" function to the "reset password" feature. I can't tell whether this is an oversight, or an instance of "designed obsolescence", in which your lifetime account is limited by the lifetime of your email address. 
Hopefully someone more informed can shed some light on this topic. 

Also, the GNU/linux support feature is really useful. Kudos to @thecodefactory for putting it together.

**Comment by Alexanderblaq91** [comment]
@bradfordcasey 

I believe this issue as been fixed on  the android side I have an s6 running MM and I am able to add the extra characters.... but more importantly I came across this literally 10secs ago so hope this will help...LOOKS like anon finally stepped up there game now we can use anon vpn form app store  

https://www.anonvpn.io/android_instructions.php

**Comment by bradfordcasey** [comment]
Nice find! Thanks for passing it along. Hopefully the next Samsung Note user that has the same problem will come across this solution.

**Pull request closed without merging**
