### PR TITLE
Allow a UDP based configuration for the ProXPN nodes that support it.

### PR DESCRIPTION
**Pull request by thecodefactory**
This significantly increases the number of hosts available to the end
user and makes this tool much more versatile.

### CODE REVIEW

**Comment by MattSurabian** [comment]
Thanks for this! 

I'd like to adjust the installer script to generate the UDP config instead of copying it on script run as I don't want folks to necessarily need to have a full checkout of this in the same location the script is run from. I don't mind making this change if you don't have the time for it.

The only other thought I have is regarding the IP addresses, there's some discussion in #25 and #29 about the pros and cons of DNS based endpoints vs IP address. Does ProXPN have UDP specific DNS entries we could use in the hosts list or is the IP necessary for this to function? It's possible supporting UDP will push that discussion in favor of IP addresses depending on the answer.

Thanks again for taking the time to open this PR, I very much want to get it merged once we finalize these discussion points.

**Comment by MattSurabian** [comment]
For some additional context on the IP vs FQDN thing: I want to make sure new adopters of this code feel confident that they know what servers they are connecting to. Because this is a third party script that isn't officially supported it seemed using fully qualified domain names was the way to accomplish this. Increasingly though maybe that's not the case. If you have any thoughts on how we could accomplish that or even a counter point to this concern I'd love to hear it.

**Comment by thecodefactory** [comment]
Personally, I prefer IP based configurations for VPNs, just due to leaking slightly less information -- but it doesn't really matter either way.  The IPs were pulled directly from the xml file and I wasn't sure if the key was a valid hostname, so I didn't want to chance it and instead chose something that I knew worked.  If anything, I'd prefer seeing the entire options list being generated from the xml file, but that would likely be a script re-write to something like python, making it much more manageable (at least to me).

You can see from the pull request, I also chose IP addresses to distinguish between tcp and udp endpoints, but that was a hack of convenience.  It won't work as-is if all sites for both protocols are broken into FQDNs or moved to IP addresses (without some change in logic).

**Comment by thecodefactory** [comment]
Also, I don't think new adopters of this code would feel any more or less confident in using it if it had IPs or hostnames referenced from a specified source.  I was able to see what it was doing, and verified it myself from the OS X dmg.  I don't expect everyone to do that, but for those that want to, it's an option.

From a user perspective, choosing a menu option for a location doesn't impact that either.  What an end-user will probably see is the connection/initialization data once connected, and as long as something in there resembles the ProXPN connection (seen in the verify steps showing the certificate subject information), it's likely ok (although I know that can be spoofed, but it would indicate a larger breach on your system since the configs would've been modified as well to connect properly).

**Comment by MattSurabian** [comment]
Good points. Since we can reference the publicly available list of exit nodes as provided by ProXPN I think you're right that there's enough to make folks feel secure. 

Someone referenced in an old issue that they were making a python version that did request and parse the XML not sure the status of that project today though.

**Comment by MattSurabian** [comment]
I think I found a simple way to handle this, I'll be putting up a PR tomorrow.

**Comment by MattSurabian** [comment]
Closing this in favor of #33, thanks for pushing me to make this happen and for providing such beneficial discussion!

**Pull request closed without merging**
