### PR TITLE
Update proxpn

### PR DESCRIPTION
**Pull request by Pysis868**
Added check if script is being run as user with root privileges, and if not, exit immediately since successful operation involving the 'ip route' command would not be possible.

### CODE REVIEW

**Comment by MattSurabian** [comment]
I think this might be missing the commit which adds the new check? 

Some free form thoughts on the feature:
I'm not sure if we should automatically exit, maybe just warn the user and instead of asking the user if the want to run the command exit and output the command the user should run.

It's tricky because I'm not sure how privacy conscious folks who use this are. I know many people that refuse to run scripts as `sudo` unless the understand every line of it. The hope was to offer those users a middle ground by auto-generating the command they should run.

I suspect if we merged this, adding a flag like `--dry-run` might suffice for those such users, wherein the new sudo check would be bypassed and no confirmation to run the command would be shown and it would just be sent to `stdout`.

**Comment by MattSurabian** [comment]
So definitely convinced we should address this. Wrote up thoughts in #6 for feature behavior. Basically if the `--dry-run` flag is passed _or_ the command is run without `sudo` the script will operate in `dry-run` mode.

**Comment by Pysis868** [comment]
Sorry about the lacking commit; I went through the GitHub interface directly and it seems to have created 2 different branches with the split changes.  I have since merged it and added 1 more small commit fully capturing my thoughts.

It's not a large script, or one that satisfies a large purpose, so those people could certainly inspect it and leave where control is turned over to the `openvpn` executable, trusting it at that point.

I see #6, and I'm not sure what a dry run would accomplish, even at least for this non-sudo case.  If it would load the configuration, maybe it could do so by loading & validating that information, but it probably should not attempt to contact the VPN server at all.  I've also seen security conscious people to want these things to fail instead of 'partially work', so they have a clearer idea that they need to tend to something, without accidentally exposing any sensitive information, which is what prompted me to exit the script with an error message and status.

Maybe in either the dry run flag case, or the non-sudo execution case, we could go ahead and add this code in now, and always build on top of it later.

**Comment by MattSurabian** [comment]
I agree that `--dry-run` should not contact the VPN server at all. 

In my view this script has two potential uses, with the main use being to actually do the connection all the time to ProXPN. In this case it must be run as `sudo` or it will not work. The alternative approach is for a user to get all the way to the prompt:

```
The following command will be run:
/usr/bin/openvpn --config /etc/proxpn/proxpn.ovpn --remote se1.proxpn.com 443 --auth-user-pass /etc/proxpn/login.conf --auth-nocache
```

Then bail out by refusing to attempt connecting. They then copy the `openvpn` command directly and use that via an alias or similar going forward. In that use case `sudo` doesn't have to be used.

My hope is that deprecating `-y` and the above prompt in favor of `--dry-run` and forcing dry run mode when the user has not `sudo`'d helps users in the first group have one less interaction and users in the second group not have a script that partially works when they don't run it as `sudo`. In dry run mode the script would end with something like:

```
The following OpenVPN command can be used to connect to ProXPN:
/usr/bin/openvpn --config /etc/proxpn/proxpn.ovpn --remote se1.proxpn.com 443 --auth-user-pass /etc/proxpn/login.conf --auth-nocache
```

At any rate I agree we can merge this and build on top of it. Thanks for the submission and for bringing this discussion forward.

**Comment by MattSurabian** [comment]
:+1:

**Comment by Pysis868** [comment]
Thanks for merging that.  I did have one last thought about the dry run case through normal operation.  If a user wants to run the script without the flag, they expect to run, and anything less of setting up a secure connection should at least present an error status that does not reflect success, so that other scripts could be notified.

**Comment by MattSurabian** [comment]
Yeah that's an interesting point. I've opened #8 to capture this suggestion.

**Pull request merged**
